---
title: "Untitled"
format: html
editor: visual
---

```{r include=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)
library(htmlwidgets)
library(reactablefmtr)
```

```{r include=FALSE}
train <- read_csv("Training.csv") |> 
  #mutate(date = mdy(date)) |> 
  arrange(group, subgroup, subject, tool, language) |> 
  select( group,subgroup, subject, course, date, tool, language, theory, practice, total )
```

```{r include=FALSE}
traindandrea <- train |> 
  reactable(
    # Theme
    theme = reactableTheme(
      borderColor = "#dfe2e5",
      stripedColor = "#f6f8fa",
      highlightColor = "#f0f5f9",
      cellPadding = "8px 12px",
      style = list(
        fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"
      ),
      searchInputStyle = list(width = "25%")
    ),
    # Parameters
    groupBy = c("group","subgroup"),
    striped = TRUE,
    bordered = TRUE,
    searchable = TRUE,
    language = reactableLang( searchPlaceholder = "SEARCH FOR A COURSE..." ),
    showSortIcon = TRUE,
    pagination = FALSE,
    defaultExpanded = TRUE,
    # Columns
    columns = list(
      group = colDef( name =  "Group", width = 150, filterable = FALSE),
      subgroup = colDef( name =  "Subgroup", width = 150, filterable = FALSE),
      subject = colDef( name =  "Subject" ,width = 150, filterable = FALSE),
      course = colDef( name =  "Course", width = 350, filterable = FALSE ),
      tool = colDef( name =  "Tool", width = 100, filterable = FALSE ),
      language = colDef( name =  "Prog. Language", width = 100, filterable = FALSE ),
      date = colDef( name =  "Date" , width = 120, format = colFormat(date = TRUE)),
      theory = colDef( name =  "Hours of Theory", width = 100, aggregate = "sum",
                       footer = JS("function(column,state){
                         let total = 0
                         state.sortedData.forEach(function(row){
                           total += row[column.id]
                         })
                         return total
                        }")
      ),
      practice = colDef( name =  "Hours of Practice", width = 100,aggregate = "sum",
                         footer = JS("function(column,state){
                         let total = 0
                         state.sortedData.forEach(function(row){
                           total += row[column.id]
                         })
                         return total
                        }")
                         
      ),
      
      total = colDef( name =  "Hours Total",
                      width = 100,
                      aggregate = "sum",
                      footer = JS("function(column,state){
                         let total = 0
                         state.sortedData.forEach(function(row){
                           total += row[column.id]
                         })
                         return total
                        }")
      ))
    ) |> 
  add_title( title = "Extention Training")|> 
  add_subtitle(subtitle = "Joao Luiz D'Andrea",
               font_size = 20,
               font_color = '#666666',
               margin = reactablefmtr::margin(t=10,r=0,b=15,l=0),
               font_weight = "normal") |> 
  add_source(
    source = "Author: Joao Luiz D Andrea",
    font_style = 'italic',
    font_weight = 'bold'
  )


```

```{r}
saveWidget(traindandrea, file="index.html")
```
